name: Prison
version: '1.0-SNAPSHOT'
main: me.deployable.prison.Prison
api-version: 1.20
depend: [Vault]
commands:
  ranks:
    description: view all ranks
    usage: /<command>
  rankup:
    description: rankup to the next rank
    usage: /<command>